name: CI/CD para Angular no S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"  # Substitua com sua região AWS

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar o Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Instalar dependências
      run: npm install

    - name: Construir a aplicação Angular
      run: npm run build 

    - name: Configurar AWS CLI
      run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set default.region $AWS_DEFAULT_REGION

    - name: Fazer upload para o S3
      run: aws s3 sync dist/ s3://jacinto-software-deploy-s3
